package com.promanage.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class Project {

    // Fields corresponding to database columns
    private int projectId;
    private String title;
    private int deadline;
    private BigDecimal revenue;
    private String status;
    private LocalDateTime createdAt;

    // Constructors


//  Default constructor
    public Project() {
        this.status = "PENDING";
        this.createdAt = LocalDateTime.now();
    }

//   Constructor for adding new project (without ID)
//   ID will be auto-generated by database
    public Project(String title, int deadline, BigDecimal revenue) {
        this.title = title;
        this.deadline = deadline;
        this.revenue = revenue;
        this.status = "PENDING";
        this.createdAt = LocalDateTime.now();
    }

//  Constructor with all fields (for retrieving from database)
    public Project(int projectId, String title, int deadline, BigDecimal revenue,String status, LocalDateTime createdAt) {
        this.projectId = projectId;
        this.title = title;
        this.deadline = deadline;
        this.revenue = revenue;
        this.status = status;
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public int getProjectId() {
        return projectId;
    }

    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getDeadline() {
        return deadline;
    }

    public void setDeadline(int deadline) {
        this.deadline = deadline;
    }

    public BigDecimal getRevenue() {
        return revenue;
    }

    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Utility Methods

//  Returns a formatted string representation of the project
    @Override

    public String toString() {
        return String.format("Project [ID=%d, Title=%s, Deadline=%d days, Revenue=₹%.2f, Status=%s]", projectId, title, deadline, revenue, status);
    }

//  Validates if the project data is valid
    public boolean isValid() {
        return title != null && !title.trim().isEmpty()
                && deadline > 0 && deadline <= 5
                && revenue != null && revenue.compareTo(BigDecimal.ZERO) > 0;
    }

//  Compare projects by revenue (for sorting in descending order)

    public static int compareByRevenue(Project p1, Project p2) {
        return p2.getRevenue().compareTo(p1.getRevenue());
    }
}